version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mern_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: mern_server
    ports:
      - "5001:5000"
    volumes:
      - ./server:/usr/src/app
      - server_node_modules:/usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern_db
      - PORT=5000
    command: npm run dev

  client:
    build: ./client
    container_name: mern_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - client_node_modules:/usr/src/app/node_modules
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    command: npm start

volumes:
  mongo-data:
  server_node_modules:
  client_node_modules:
